### ISSUE TITLE
Flags are float64?

### ISSUE THREAD

**Issue by awst-baum** [TUW-GEO/smos#5]
When using the `SMOSTs` reader, the SMOS flags are returned as float64 arrays. Is that intentional?

SMOS doc says:
```
Read Flags with Matlab :
>> if flag < 0
    flag = dec2bin(typecast(int8(flag),'uint8')) ;
    else
    flag = dec2bin(flag,8) ;
    end
```

**Comment by wpreimes** [comment]
I think the problem is that when there are no measurements there are also no ``flags``, i.e. there are ``NaNs`` in the flag images and therefore the column can't contain ``int`` values only. It might make sense to fill the flag columns with some integer when storing the time series... therefore I leave this issue open for now and will implement something if it doesn't increase data size too much.
